### ISSUE TITLE
Add description how to operate the PLC without HMI

### ISSUE THREAD

**Issue by EndyCZ** [industrial-edge/miscellaneous#9]
I propose to just add comment how you can operate the PLC using the hmisignals in the GDB. Just toggle the HMI_Start tag to start. and toggle HMI_stop to stop.

**Comment by HummelN7872** [comment]
Use the correct PG/PC setting to connection the HMI simulation to a real PLC

**Comment by HummelN7872** [comment]
Add infobox "Please make sure your PG/PC interfaces settings are configured properly"

**Comment by EvaKaul** [comment]
Issue solved with latest version
